server:
  port: 8082

spring:
  cloud:
    function:
      definition: order
    stream:
      bindings:
        order-in-0:
          destination: "order"
      kafka:
        binder:
          brokers: localhost:29092
