server:
  port: 8082

spring:
  cloud:
    function:
      definition: customer
    stream:
      bindings:
        customer-in-0:
          destination: "customer"
      kafka:
        binder:
          brokers: localhost:29092
