spring:
  cloud:
    function:
      definition: customer
    stream:
      bindings:
        customer-out-0:
          destination: "customer"
      kafka:
        binder:
          brokers: localhost:29092
